spring:
  application:
    name: spring-mybatis
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  jackson:
    #设置空如何序列化
    #default-property-inclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true
    property-naming-strategy: LOWER_CAMEL_CASE
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**

server:
  port: 8081
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations:
    classpath: /Mapper/*.xml
encode:
  secret:
    $adhajkshdgghjds
feign:
  resource-server-url: http://localhost:8082
  sys-user-url: /sysUser
  sys-client-url: /sysClient
  sys-role-url: /sysRole
  sys-index-url: /sysIndex
oauth:
  metadata:
    issuer: http://localhost:8081
    authorization-endpoint: ${oauth.metadata.issuer}/user/oauth2/authorize
    token-endpoint: ${oauth.metadata.issuer}/user/oauth2/token
    token-endpoint-auth-methods-supported:
      - client_secret_basic
    token-endpoint-auth-signing-alg-values-supported:
      - ES256
    jwks-uri: ${oauth.metadata.issuer}/.well-known/jwks.json
    response-types-supported:
      - code
    grant-types-supported:
      - authorization_code
      - refresh_token
#  指定日志级别 把springboot的所有日志修改成为debug
#logging:
#  level:
#    root: info
#    com.wojucai.service.UserService: debug
#  config: classpath:logback.xml
#  file:
#    path: logs
